language: R
sudo: false
cache: packages
before_install:
- openssl aes-256-cbc -K $encrypted_c6d33e1d02b0_key -iv $encrypted_c6d33e1d02b0_iv
  -in tests/testthat/hosted_keys.rda.enc -out tests/testthat/hosted_keys.rda -d
